// 1. 關卡名稱對照表
const STAGES_DATA = {
    "03": "最初的岩壁",
    "07": "史萊姆合唱團",
    "18": "爆裂裝置——爆破怪",
    "20": "亞拉戈鬥技場(提豐&奧爾特羅斯)",
    "21": "阿皮狄馬",
    "24": "艾匹羅基 / 鬥場抄寫員",
    "25": "阿波卡里普斯",
    "29": "水之式神"
};

// 2. 成就說明對照表
const ACHIEVEMENT_DOCS = {
    "標準通關": "在規定時間內擊敗所有敵人。",
    "水系大師": "僅使用水屬性青魔法完成挑戰。",
    "高階法師": "僅使用 4 星或 5 星的青魔法完成挑戰。",
    "十招足以": "全程使用的青魔法種類不超過 10 種。",
    "四招足以": "全程使用的青魔法種類不超過 4 種。"
};

// 3. 完整技能庫 (124招)
const SKILLS_LIBRARY = [
    { no: 1, spell: "水槍", patch: "4.5", source: "自動習得" },
    { no: 2, spell: "火炎放射", patch: "4.5", source: "布雷福洛克斯野營地(6號哥布林坦克) / 密約之塔(獨爪妖禽)" },
    { no: 3, spell: "水紋吐息", patch: "4.5", source: "亞拉戈鬥技場(奧爾特羅斯) / 假面狂歡20 / 利維亞桑" },
    { no: 4, spell: "狂亂", patch: "4.5", source: "天狼星燈塔(祖) / 外地拉諾西亞(角祖)" },
    { no: 5, spell: "鑽頭砲", patch: "4.5", source: "北薩納蘭(廢棄先鋒) / 野營地(哥布林裝甲) / 南方堡 / 魔導城" },
    { no: 6, spell: "高壓電流", patch: "4.5", source: "巴哈姆特大迷宮 邂逅1&2 / 假面狂歡15(鬥獸系統)" },
    { no: 7, spell: "若隱若現", patch: "4.5", source: "北薩納蘭(菲蘭德副耀士) / 無限城市街古蹟 / 塔姆塔拉墓園" },
    { no: 8, spell: "最終刺針", patch: "4.5", source: "中拉諾西亞(殺手胡蜂) / 喀恩埋沒聖堂(聖堂蜂)" },
    { no: 9, spell: "苦悶之歌", patch: "4.5", source: "天狼星燈塔(塞壬)" },
    { no: 10, spell: "怒視", patch: "4.5", source: "黃金谷(數幣巨人) / 中薩納蘭S怪(布隆特斯)" },
    { no: 11, spell: "平原震裂", patch: "4.5", source: "各區巨像 / 銅鈴銅山 / 喀恩埋沒聖堂 / 假面狂歡25" },
    { no: 12, spell: "怒髮衝冠", patch: "4.5", source: "黑衣森林東部林區(狂野疣豬)" },
    { no: 13, spell: "白風", patch: "4.5", source: "圖騰：習得10個技能 / 無限城的死鬥(恩奇都)" },
    { no: 14, spell: "5級石化", patch: "4.5", source:	 "靜語莊園(莊園守衛) / 古代人迷宮(詛咒之眼)" },
    { no: 15, spell: "鋒利菜刀", patch: "4.5", source: "放浪神古神殿(冬貝利王) / 高地拉諾西亞A怪(瑪貝利)" },
    { no: 16, spell: "冰棘屏障", patch: "4.5", source: "森林中央林區(搗蛋小鬼) / 靜語莊園 / 假面狂歡25" },
    { no: 17, spell: "吸血", patch: "4.5", source: "各地蝙蝠類怪物 / 靜語莊園 / 喀恩埋沒聖堂 / 黃金谷" },
    { no: 18, spell: "橡果炸彈", patch: "4.5", source: "各地幼體樹精 / 森林中央S怪 / 無限城古堡(多節樹精)" },
    { no: 19, spell: "投彈", patch: "4.5", source: "各地哥布林類怪物 / 布雷福洛克斯野營地" },
    { no: 20, spell: "破防", patch: "4.5", source: "圖騰：習得5個技能" },
    { no: 21, spell: "自爆", patch: "4.5", source: "西薩納蘭(滑行爆彈怪) / 銅鈴銅山 / 靜語莊園 / 樵鳴洞" },
    { no: 22, spell: "融合", patch: "4.5", source: "圖騰：習得20個技能" },
    { no: 23, spell: "拍掌", patch: "4.5", source: "中薩納蘭(盧恩人) / 東拉諾西亞(盧恩人)" },
    { no: 24, spell: "投擲沙丁魚", patch: "4.5", source: "東拉諾西亞(碧企鵝) / 東拉諾西亞B怪(血腥瑪麗)" },
    { no: 25, spell: "鼻息", patch: "4.5", source: "亞拉戈鬥技場(提豐) / 假面狂歡20(提豐)" },
    { no: 26, spell: "4星噸", patch: "4.5", source: "亞拉戈鬥技場(奧爾特羅斯)" },
    { no: 27, spell: "詭異視線", patch: "4.5", source: "摩杜納理符(暗黑扎哈克) / 無限城古堡 / 古代人迷宮" },
    { no: 28, spell: "臭氣", patch: "4.5", source: "森林中央林區(套索花) / 摩杜納(魔界花) / 黃金谷(魔界花)" },
    { no: 29, spell: "超硬化", patch: "4.5", source: "石衛塔(庫卡龍龜) / 皇都保衛戰 / 龍堡參天高地(塔拉斯克)" },
    { no: 30, spell: "強力守護", patch: "4.5", source: "圖騰：習得10個技能" },
    { no: 31, spell: "滑舌", patch: "4.5", source: "中薩納蘭(毒蟾蜍) / 西薩納蘭 / 東拉諾西亞" },
    { no: 32, spell: "油性分泌物", patch: "4.5", source: "西薩納蘭(癡笑巨蟾蜍)" },
    { no: 33, spell: "寒冰咆哮", patch: "4.5", source: "樵鳴洞(奇美拉) / 死化奇美拉討伐戰 / 北薩納蘭FATE" },
    { no: 34, spell: "雷電咆哮", patch: "4.5", source: "樵鳴洞 / 死化奇美拉 / 假面狂歡21&25" },
    { no: 35, spell: "導彈", patch: "4.5", source: "無限城的死鬥(恩奇都)" },
    { no: 36, spell: "千根針", patch: "4.5", source: "南薩納蘭(仙人刺舞蹈家) / 樵鳴洞(仙人刺逃兵)" },
    { no: 37, spell: "噴墨", patch: "4.5", source: "逆轉要害沙斯塔夏溶洞(克拉肯)" },
    { no: 38, spell: "火投槍", patch: "4.5", source: "武裝聖域放浪神古神殿(寇黑加)" },
    { no: 39, spell: "月之笛", patch: "4.5", source: "圖騰：完成10種假面狂歡" },
    { no: 40, spell: "甩尾", patch: "4.5", source: "逆轉要害沙斯塔夏溶洞(真紅龍蝦) / 基拉巴尼亞山區" },
    { no: 41, spell: "精神衝擊", patch: "4.5", source: "塔姆塔拉墓園(加爾梵斯) / 南森林S怪(奪心魔)" },
    { no: 42, spell: "死亡宣告", patch: "4.5", source: "圖騰：完成20種假面狂歡" },
    { no: 43, spell: "驚奇光", patch: "4.5", source: "摩杜納(靜水泥沼蝾螈) / 野營地(水棲蝾螈)" },
    { no: 44, spell: "飛翎雨", patch: "4.5", source: "迦樓羅殲殛戰" },
    { no: 45, spell: "噴發", patch: "4.5", source: "伊弗利特討伐/殲滅/殲殛戰" },
    { no: 46, spell: "山崩", patch: "4.5", source: "泰坦殲滅/殲殛戰" },
    { no: 47, spell: "轟雷", patch: "4.5", source: "拉姆殲滅/殲殛戰" },
    { no: 48, spell: "冰雪亂舞", patch: "4.5", source: "希瓦殲殛戰" },
    { no: 49, spell: "水神的面紗", patch: "4.5", source: "利維亞桑殲滅/殲殛戰" },
    { no: 50, spell: "高山氣流", patch: "5.15", source: "阿巴拉提亞雲海(獅鷲) / 暮衛塔(獅身巨鷹)" },
    { no: 51, spell: "萬變水波", patch: "5.15", source: "機神城 啟動3(有生命活水) / 假面狂歡29" },
    { no: 52, spell: "狂風暴雪", patch: "5.15", source: "庫爾扎斯西部高地(大腳板岩雪人)" },
    { no: 53, spell: "生物電", patch: "5.15", source: "阿巴拉提亞雲海(雷牙)" },
    { no: 54, spell: "寒光", patch: "5.15", source: "機神城 啟動1&2(浮士德)" },
    { no: 55, spell: "深淵貫穿", patch: "5.15", source: "內陸低地(上級惡魔) / 迦巴勒幻想圖書館" },
    { no: 56, spell: "嘰嘰喳喳", patch: "5.15", source: "阿巴拉提亞雲海(猴面雀)" },
    { no: 57, spell: "怪音波", patch: "5.15", source: "魔大陸阿濟茲拉(疫蟲)" },
    { no: 58, spell: "澎澎療傷", patch: "5.15", source: "莫古力賢王殲滅/殲殛戰(庫普洛·奇普)" },
    { no: 59, spell: "哥布防禦", patch: "5.15", source: "內陸低地A怪 / 機神城 天動2" },
    { no: 60, spell: "魔法錘", patch: "5.15", source: "迦巴勒幻想圖書館(阿班達) / 假面狂歡24" },
    { no: 61, spell: "防御指示", patch: "5.15", source: "聖茉夏娜植物園(鷹鋒女王)" },
    { no: 62, spell: "蛙腿", patch: "5.15", source: "龍堡內陸低地(智蛙)" },
    { no: 63, spell: "音爆", patch: "5.15", source: "雲海(安祖) / 天狼星燈塔(祖)" },
    { no: 64, spell: "口笛", patch: "5.15", source: "阿巴拉提亞雲海(長頸駝)" },
    { no: 65, spell: "白騎士之旅", patch: "5.15", source: "伊修加德教皇廳(白騎士)" },
    { no: 66, spell: "黑騎士之旅", patch: "5.15", source: "伊修加德教皇廳(黑騎士)" },
    { no: 67, spell: "5級致死一擊", patch: "5.15", source: "迦巴勒幻想圖書館(64頁)" },
    { no: 68, spell: "火箭炮", patch: "5.15", source: "巴埃薩長城(武裝重甲)" },
    { no: 69, spell: "永恆射線", patch: "5.15", source: "機神城 啟動4(操縱者)" },
    { no: 70, spell: "仙人盾", patch: "5.15", source: "喀恩埋沒聖堂(仙人刺守衛)" },
    { no: 71, spell: "復仇衝擊", patch: "5.15", source: "圖騰：習得50個技能" },
    { no: 72, spell: "天使低語", patch: "5.15", source: "圖騰：完成30個假面狂歡" },
    { no: 73, spell: "蛻皮", patch: "5.15", source: "無限城市街古蹟(瓦魔蛾) / 雲海(阿巴拉提亞瓦魔蛾)" },
    { no: 74, spell: "逆流", patch: "5.15", source: "翻雲霧海(雲上雙足飛龍) / 龍巢神殿" },
    { no: 75, spell: "捕食", patch: "5.15", source: "無限城市街古蹟(腐壞貪吃鬼) / 邂逅1(神杖巨蛇)" },
    { no: 76, spell: "小偵測", patch: "5.15", source: "假面狂歡24 / 迦巴勒幻想圖書館" },
    { no: 77, spell: "乙太複製", patch: "5.15", source: "天狼星燈塔Hard(第一波小怪)" },
    { no: 78, spell: "穿甲散彈", patch: "5.15", source: "羅波那殲滅/殲殛戰" },
    { no: 79, spell: "類星體", patch: "5.15", source: "索菲婭殲滅/殲殛戰" },
    { no: 80, spell: "正義飛踢", patch: "5.15", source: "機神城 律動4(殘暴正義號)" },
    { no: 81, spell: "魚叉三段", patch: "5.45", source: "延夏(惠比壽鯰魚精) / 延夏B怪(魚雷)" },
    { no: 82, spell: "霹靂霹靂", patch: "5.45", source: "延夏(惠比壽鯰魚精) / 延夏B怪(魚雷)" },
    { no: 83, spell: "掀地板之術", patch: "5.45", source: "黃金閣(道順丸)" },
    { no: 84, spell: "冷霧", patch: "5.45", source: "終末焦土(霧龍)" },
    { no: 85, spell: "讚歌", patch: "5.45", source: "吉祥天女殲滅/殲殛戰" },
    { no: 86, spell: "聖光射線", patch: "5.45", source: "歐米茄 西格瑪1(魔列車)" },
    { no: 87, spell: "污泥潑灑", patch: "5.45", source: "聖茉夏娜植物園Hard / 伊爾美格A怪" },
    { no: 88, spell: "天使的點心", patch: "5.45", source: "圖騰：達到70級" },
    { no: 89, spell: "玄結界", patch: "5.45", source: "獄之蓋(玄武)" },
    { no: 90, spell: "鬥靈彈", patch: "5.45", source: "星導寺(雙豹伊沃恩)" },
    { no: 91, spell: "鬥爭本能", patch: "5.45", source: "星導寺 / 拉諾西亞高地(高階長須豹)" },
    { no: 92, spell: "超振動", patch: "5.45", source: "基拉巴尼亞山區(恐甲螞蜓/B怪蛇仆螞蜓)" },
    { no: 93, spell: "冰焰", patch: "5.45", source: "歐米茄 德爾塔1(老者)" },
    { no: 94, spell: "芥末爆彈", patch: "5.45", source: "歐米茄 阿爾法3(歐米茄)" },
    { no: 95, spell: "龍之力", patch: "5.45", source: "圖騰：習得100個技能" },
    { no: 96, spell: "乙太火花", patch: "5.45", source: "基拉巴尼亞湖區(陀魯婆 / A怪泛光晶體)" },
    { no: 97, spell: "水力吸引", patch: "5.45", source: "斯卡拉遺蹟(凱爾派)" },
    { no: 98, spell: "水脈詛咒", patch: "5.45", source: "岩燕廟(賽太歲)" },
    { no: 99, spell: "陸行鳥隕石", patch: "5.45", source: "拉巴納斯塔 / 龍堡參天高地(追獵種陸行鳥)" },
    { no: 100, spell: "馬特拉魔法飛彈", patch: "5.45", source: "圖騰：習得100個技能" },
    { no: 101, spell: "生成外設", patch: "5.45", source: "歐米茄 阿爾法3(歐米茄)" },
    { no: 102, spell: "如意大旋風", patch: "5.45", source: "岩燕廟(齊天大聖)" },
    { no: 103, spell: "鬼宿腳", patch: "5.45", source: "朱雀鎮魂/詩魂戰" },
    { no: 104, spell: "月下彼岸花", patch: "5.45", source: "月讀殲滅/幽夜戰" },
    { no: 105, spell: "哥布林拳", patch: "6.45", source: "珂露西亞島(大哥布林) / 珂露西亞島A怪" },
    { no: 106, spell: "大迴旋", patch: "6.45", source: "馬利卡大井(大犰狳)" },
    { no: 107, spell: "刺陣", patch: "6.45", source: "安穆·艾蘭(長尾犰狳) / 薩維奈島B怪" },
    { no: 108, spell: "補水", patch: "6.45", source: "安穆·艾蘭(滑溜犰狳)" },
    { no: 109, spell: "魔法吐息", patch: "6.45", source: "圖騰：達到80級" },
    { no: 110, spell: "獸魂的憤怒", patch: "6.45", source: "諾弗蘭特(幻光狂戰士)" },
    { no: 111, spell: "玩泥球", patch: "6.45", source: "瑪托雅工作室(土泥人)" },
    { no: 112, spell: "大掃除", patch: "6.45", source: "宇宙宮(宮殿的隱者)" },
    { no: 113, spell: "紅寶石電圈", patch: "6.45", source: "紅寶石神兵破壞/狂想作戰" },
    { no: 114, spell: "魔之符文", patch: "6.45", source: "緹坦妮雅殲滅/殲殛戰" },
    { no: 115, spell: "空間轉換", patch: "6.45", source: "伊甸 覺醒1(至尊伊甸)" },
    { no: 116, spell: "加強信音", patch: "6.45", source: "格魯格火山(得到寬恕的猥褻)" },
    { no: 117, spell: "力場", patch: "6.45", source: "圖騰：習得120個技能 / 薩菲洛特殲殛戰" },
    { no: 118, spell: "斷罪飛翔", patch: "6.45", source: "無瑕靈君殲滅/殲殛戰" },
    { no: 119, spell: "雷射眼", patch: "6.45", source: "伊甸 再生4(伊甸之約)" },
    { no: 120, spell: "糖果手杖", patch: "6.45", source: "多恩美格禁園(美眼 因克·佐恩)" },
    { no: 121, spell: "必滅之炎", patch: "6.45", source: "宇宙宮(盧格斯)" },
    { no: 122, spell: "咕嚕咕嚕", patch: "6.45", source: "瑪托雅工作室(水滴精)" },
    { no: 123, spell: "默示錄", patch: "6.45", source: "亞馬烏羅提(至大災獸)" },
    { no: 124, spell: "終有一死", patch: "6.45", source: "緹坦妮雅殲滅/殲殛戰" }
];
