// data.js - 靜態資料庫 (建議不常變動的部分放在這裡)

const STAGES_DATA = {
    "01": "出道戰",
    "02": "布丁拼盤",
    "03": "最初的岩壁——希派克納",
    "04": "怪力鐵巨人——克利傑斯",
    "05": "金齒鯊兄弟",
    "06": "鐵鷹戰士",
    "07": "史萊姆合唱團",
    "08": "青之牙、紅之牙",
    "09": "七彩甜點——棉花軟糖",
    "10": "無頭王者——幽黑曲偶",
    "11": "爆前速攻",
    "12": "寄生植物——火花草",
    "13": "猩紅死妖姬——卡蜜拉",
    "14": "陪葬",
    "15": "來自亞拉戈的威脅——門獸系統",
    "16": "怪力獸王——迪克巴朗",
    "17": "剛柔鐵巨人——克利傑斯改",
    "18": "爆破死門",
    "19": "魅惑芳香——反射魔花瑞貝卡",
    "20": "著名組合——奧爾特羅斯&杜蘭",
    "21": "憤怒合成獸——阿帕德馬克",
    "22": "爆炸殲滅——炸彈之祖",
    "23": "魔獸皇太子——凶惡巨獸太子",
    "24": "異形人偶師傅——艾匹羅基",
    "25": "邪惡青魔道士——啟示者",
    "26": "強大的父親——馬巴巴之父",
    "27": "鼻息爆破死門",
    "28": "絕妙傀儡師——都藍",
    "29": "水與火之歌",
    "30": "世界第一劍士——齊格弗里德",
    "31": "黃金頭巾——模仿師格格",
    "32": "黃金鬥士——金德爾"
};

const ACHIEVEMENT_DOCS = {
    "高速通關": "在挑戰時間內通關",
    "標準通關": "在標準時間內通關",
    "十招足以": "使用的青魔法不少於 2 種、不超過 10 種",
    "四招足以": "使用的青魔法不少於 2 種、不超過 4 種",
    "未受傷害": "未受到傷害",
    "未曾恢復": "未使用恢復 HP 的魔法",
    "打斷高手": "打斷敵人的詠唱",
    "不緊不慢": "未使用衝刺",
    "火系大師": "只使用火與無屬性青魔法通關",
    "水系大師": "只使用水與無屬性青魔法通關",
    "土系大師": "只使用土與無屬性青魔法通關",
    "風系大師": "只使用風與無屬性青魔法通關",
    "冰系大師": "只使用冰與無屬性青魔法通關",
    "雷系大師": "只使用雷與無屬性青魔法通關",
    "元素大師": "用出水、火、土、冰、風、雷屬性攻擊",
    "技能大師": "用出水、火、土、冰、風、雷、斬擊、突刺、打擊屬性攻擊",
    "弱化高手": "賦予敵人的弱化效果達到 6 種或更多",
    "弱化專家": "賦予敵人的弱化效果達到 9 種或更多",
    "物理大師": "只使用物理攻擊的青魔法通關",
    "高階法師": "只使用四星五星的青魔法通關",
    "初階法師": "只使用一星二星的青魔法通關",
    "四面神通": "用出不少於 4 種從面部放射的青魔法",
    "八面神通": "用出不少於 8 種從面部放射的青魔法",
    "恢復大師": "用出澎澎療傷、蛻皮、白風"
};

const SKILLS_LIBRARY = [
    { no: 1, spell: "水槍", patch: "4.5", source: "自動習得" },
    { no: 2, spell: "火炎放射", patch: "4.5", source: "布雷福洛克斯野營地" },
    { no: 3, spell: "水紋吐息", patch: "4.5", source: "利維亞桑" },
    { no: 4, spell: "狂亂", patch: "4.5", source: "天狼星燈塔" },
    { no: 5, spell: "鑽頭砲", patch: "4.5", source: "北薩納蘭" },
    { no: 6, spell: "高壓電流", patch: "4.5", source: "巴哈姆特大迷宮" },
    { no: 7, spell: "若隱若現", patch: "4.5", source: "真/極迦樓羅" },
    { no: 8, spell: "最終刺針", patch: "4.5", source: "中拉諾西亞-殺手蜂" },
    { no: 9, spell: "苦悶之歌", patch: "4.5", source: "無限城古堡" },
    { no: 10, spell: "怒視", patch: "4.5", source: "黃金谷" },
    { no: 11, spell: "平原震裂", patch: "4.5", source: "真/極泰坦" },
    { no: 12, spell: "怒髮衝冠", patch: "4.5", source: "真/極拉姆" },
    { no: 13, spell: "白風", patch: "4.5", source: "圖騰：10個技能" },
    { no: 14, spell: "5級石化", patch: "4.5", source: "無限城古堡" },
    { no: 15, spell: "鋒利菜刀", patch: "4.5", source: "放浪神古神廟" },
    { no: 16, spell: "冰棘屏障", patch: "4.5", source: "西部高地" },
    { no: 17, spell: "吸血", patch: "4.5", source: "西部高地" },
    { no: 18, spell: "橡實炸彈", patch: "4.5", source: "中森林-樹精" },
    { no: 19, spell: "投彈", patch: "4.5", source: "外地拉諾西亞" },
    { no: 20, spell: "破防", patch: "4.5", source: "西薩納蘭" },
    { no: 21, spell: "自爆", patch: "4.5", source: "中薩納蘭" },
    { no: 22, spell: "融合", patch: "4.5", source: "聖教托爾丹大教堂" },
    { no: 23, spell: "拍掌", patch: "4.5", source: "圖騰：50個技能" },
    { no: 24, spell: "投擲沙丁魚", patch: "4.5", source: "東拉諾西亞-阿普卡魯" },
    { no: 25, spell: "鼻息", patch: "4.5", source: "屠龍戰記" },
    { no: 26, spell: "4星噸", patch: "4.5", source: "機神城 啟動2" },
    { no: 27, spell: "詭異視線", patch: "4.5", source: "機神城 律動4" },
    { no: 28, spell: "臭氣", patch: "4.5", source: "圖騰：10場狂歡" },
    { no: 29, spell: "超硬化", patch: "4.5", source: "皇都保衛戰" },
    { no: 30, spell: "強力守護", patch: "4.5", source: "圖騰：10個技能" },
    { no: 31, spell: "滑舌", patch: "4.5", source: "中拉諾西亞-大蟾蜍" },
    { no: 32, spell: "油性分泌物", patch: "4.5", source: "溶洞(Hard)" },
    { no: 33, spell: "寒冰霧", patch: "4.5", source: "真/極希瓦" },
    { no: 34, spell: "怒號", patch: "4.5", source: "真/極希瓦" },
    { no: 35, spell: "導彈", patch: "4.5", source: "真吉爾伽美什" },
    { no: 36, spell: "千針刺", patch: "4.5", source: "南薩納蘭-仙人刺" },
    { no: 37, spell: "墨汁砲", patch: "4.5", source: "薩斯塔夏溶洞" },
    { no: 38, spell: "火焰噴射", patch: "4.5", source: "默約之塔" },
    { no: 39, spell: "月下彼岸花", patch: "5.15", source: "月讀殲滅戰" },
    { no: 40, spell: "死亡輪盤", patch: "4.5", source: "假面狂歡 25" },
    { no: 41, spell: "精神衝擊", patch: "4.5", source: "塔姆拉墓園" },
    { no: 42, spell: "死宣", patch: "4.5", source: "假面狂歡 20" },
    { no: 43, spell: "驚奇光", patch: "4.5", source: "摩爾波爾類怪" },
    { no: 44, spell: "羽毛箭", patch: "4.5", source: "西部高地-安祖" },
    { no: 45, spell: "破防", patch: "4.5", source: "圖騰：5個技能" },
    { no: 46, spell: "山崩", patch: "4.5", source: "真/極泰坦" },
    { no: 47, spell: "震撼彈", patch: "4.5", source: "中拉諾西亞" },
    { no: 48, spell: "水砲 (舊)", patch: "4.5", source: "自動習得" },
    { no: 49, spell: "水流環", patch: "4.5", source: "圖騰：20個技能" },
    { no: 50, spell: "高山之風", patch: "4.5", source: "真/極迦樓羅" },
    { no: 51, spell: "放電", patch: "4.5", source: "真/極拉姆" },
    { no: 52, spell: "狂風暴雨", patch: "4.5", source: "真/極迦樓羅" },
    { no: 53, spell: "電解", patch: "4.5", source: "真/極拉姆" },
    { no: 54, spell: "水神之怒", patch: "4.5", source: "真/極利維亞桑" },
    { no: 55, spell: "炎神之牙", patch: "4.5", source: "真/極伊弗利特" },
    { no: 56, spell: "千針刺強化", patch: "4.5", source: "假面狂歡" },
    { no: 57, spell: "怪音波強化", patch: "4.5", source: "假面狂歡" },
    { no: 58, spell: "魔法錘", patch: "4.5", source: "死者宮殿 10層" },
    { no: 59, spell: "哥布林防禦", patch: "4.5", source: "機神城 天動4" },
    { no: 60, spell: "魔法爆裂", patch: "4.5", source: "聖教托爾丹大教堂" },
    { no: 61, spell: "防禦指令", patch: "4.5", source: "機神城 律動4" },
    { no: 62, spell: "青蛙之歌", patch: "4.5", source: "低地森林" },
    { no: 63, spell: "音爆", patch: "4.5", source: "西部高地-安祖" },
    { no: 64, spell: "強襲", patch: "4.5", source: "圖騰：30個技能" },
    { no: 65, spell: "水流噴射", patch: "4.5", source: "利維亞桑" },
    { no: 66, spell: "火柱", patch: "4.5", source: "伊弗利特" },
    { no: 67, spell: "五指劍", patch: "4.5", source: "極吉爾伽美什" },
    { no: 68, spell: "天火", patch: "4.5", source: "機神城 啟動4" },
    { no: 69, spell: "永恆射線", patch: "4.5", source: "機神城 律動4" },
    { no: 70, spell: "加農砲", patch: "4.5", source: "機神城 天動4" },
    { no: 71, spell: "復仇之拳", patch: "4.5", source: "機神城 律動4" },
    { no: 72, spell: "聖火", patch: "4.5", source: "假面狂歡 30" },
    { no: 73, spell: "赤熱吐息", patch: "5.15", source: "皇都保衛戰" },
    { no: 74, spell: "反射", patch: "5.15", source: "假面狂歡 27" },
    { no: 75, spell: "吞噬", patch: "5.15", source: "真/極俾斯麥" },
    { no: 76, spell: "冷氣", patch: "5.15", source: "真/極希瓦" },
    { no: 77, spell: "以太複製", patch: "5.15", source: "聖教托爾丹大教堂" },
    { no: 78, spell: "貫穿", patch: "5.15", source: "圖騰：80個技能" },
    { no: 79, spell: "量子碎裂", patch: "5.15", source: "機神城 天動4" },
    { no: 80, spell: "正義踢", patch: "5.15", source: "機神城 律動4" },
    { no: 81, spell: "馬特拉魔術", patch: "5.15", source: "圖騰：100個技能" },
    { no: 82, spell: "嗶嗶信號", patch: "5.15", source: "機神城 啟動2" },
    { no: 83, spell: "疊圖", patch: "5.15", source: "機神城 律動4" },
    { no: 84, spell: "冷卻", patch: "5.15", source: "機神城 啟動4" },
    { no: 85, spell: "利爪", patch: "5.15", source: "機神城 律動4" },
    { no: 86, spell: "聖光", patch: "5.15", source: "假面狂歡 30" },
    { no: 87, spell: "超音波", patch: "5.15", source: "機神城 律動4" },
    { no: 88, spell: "天使之聲", patch: "5.15", source: "圖騰：狂歡30" },
    { no: 89, spell: "玄結界", patch: "5.45", source: "獄之蓋" },
    { no: 90, spell: "鬥爭本能", patch: "5.15", source: "高地拉諾西亞-師匠" },
    { no: 91, spell: "鬥爭", patch: "5.45", source: "歐米茄 阿爾法3" },
    { no: 92, spell: "超頻", patch: "5.45", source: "歐米茄 德爾塔4" },
    { no: 93, spell: "烈風打", patch: "5.45", source: "真/極白虎" },
    { no: 94, spell: "鬼宿腳", patch: "5.45", source: "真/極朱雀" },
    { no: 95, spell: "屠龍", patch: "5.45", source: "真/極神龍" },
    { no: 96, spell: "以太火花", patch: "5.45", source: "湖畔地帶-湖畔守衛" },
    { no: 97, spell: "水爆", patch: "5.45", source: "真/極利維亞桑" },
    { no: 98, spell: "流星", patch: "5.45", source: "歐米茄 德爾塔4" },
    { no: 99, spell: "地裂", patch: "5.45", source: "真/極泰坦" },
    { no: 100, spell: "音爆強化", patch: "5.45", source: "假面狂歡 31" },
    { no: 101, spell: "地脈", patch: "5.45", source: "真/極拉姆" },
    { no: 102, spell: "赤紅聖歌", patch: "5.45", source: "真/極朱雀" },
    { no: 103, spell: "幻象", patch: "5.45", source: "歐米茄 德爾塔4" },
    { no: 104, spell: "冰爆", patch: "5.45", source: "真/極希瓦" },
    { no: 105, spell: "炎神之羽", patch: "5.45", source: "真/極伊弗利特" },
    { no: 106, spell: "強襲強化", patch: "5.45", source: "假面狂歡 31" },
    { no: 107, spell: "噴臭氣強化", patch: "5.45", source: "假面狂歡 31" },
    { no: 108, spell: "超硬化強化", patch: "5.45", source: "假面狂歡 31" },
    { no: 109, spell: "魔法吐息", patch: "5.15", source: "圖騰：100個技能" },
    { no: 110, spell: "烈風", patch: "5.45", source: "真/極迦樓羅" },
    { no: 111, spell: "落雷", patch: "5.45", source: "真/極拉姆" },
    { no: 112, spell: "地脈強化", patch: "5.45", source: "假面狂歡 31" },
    { no: 113, spell: "水神之恨", patch: "5.45", source: "真/極利維亞桑" },
    { no: 114, spell: "炎神之怒", patch: "5.45", source: "真/極伊弗利特" },
    { no: 115, spell: "死亡輪盤強化", patch: "5.45", source: "假面狂歡 32" },
    { no: 116, spell: "死宣強化", patch: "5.45", source: "假面狂歡 32" },
    { no: 117, spell: "驚奇光強化", patch: "5.45", source: "假面狂歡 32" },
    { no: 118, spell: "羽毛箭強化", patch: "5.45", source: "假面狂歡 32" },
    { no: 119, spell: "激射眼", patch: "6.45", source: "伊甸 再生4" },
    { no: 120, spell: "糖果手杖", patch: "6.45", source: "水妖幻園" },
    { no: 121, spell: "必滅之炎", patch: "6.45", source: "宇宙宮" },
    { no: 122, spell: "咕嚕咕嚕", patch: "6.45", source: "瑪托雅工作室" },
    { no: 123, spell: "啟示錄", patch: "6.45", source: "亞馬烏羅提" },
    { no: 124, spell: "終有一死", patch: "6.45", source: "緹坦妮雅" }
];
